## Упражнения по библиотеке Numpy

In [40]:
import numpy as np
import random

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

**1.** Given a random array, change the sign of elements with values between 3 and 8.

In [2]:
rand_arr = np.random.randint(0,10, size=10)
print("Original Array:", rand_arr)

rand_arr[(rand_arr >=3) & (rand_arr <=8)] = -rand_arr[(rand_arr >=3) & (rand_arr <=8)]
print("Modified Array:", rand_arr)

Original Array: [9 1 7 3 6 7 1 8 4 4]
Modified Array: [ 9  1 -7 -3 -6 -7  1 -8 -4 -4]


**2.** Заменить максимальный элемент случайного массива на 0

**2.** Replace the maximum element of a random array with 0.

In [3]:
rand_arr = np.random.randint(0,10, size=10)
print("Original Array:", rand_arr)

rand_arr[rand_arr == np.max(rand_arr)] = 0
print("Modified Array:", rand_arr)



Original Array: [8 0 4 2 2 7 9 8 4 1]
Modified Array: [8 0 4 2 2 7 0 8 4 1]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

**3.** Construct the Cartesian product of arrays (all combinations of every element). The input is a two-dimensional array.

In [13]:
def cartesian_product(arr):
  grid = np.meshgrid(*arr,indexing='ij')
  return np.stack(grid, axis=-1).reshape(-1, len(arr))

rand_arr = np.random.randint(0,10, size=(2,4))
print("Original Array:", rand_arr)

print("Cartesian Product:", cartesian_product(rand_arr))


Original Array: [[4 5 3 6]
 [2 3 3 1]]
Cartesian Product: [[4 2]
 [4 3]
 [4 3]
 [4 1]
 [5 2]
 [5 3]
 [5 3]
 [5 1]
 [3 2]
 [3 3]
 [3 3]
 [3 1]
 [6 2]
 [6 3]
 [6 3]
 [6 1]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

**4.** Given two arrays A (8x3) and B (2x2). Find the rows in A that contain elements from every row in B, regardless of the order of elements in B

In [35]:
A = np.random.randint(0,10,size=(8,3))
B = np.random.randint(0,10,size=(2,2))

print("Original Array A:", A)
print("Original Array B:", B)
B0 = set(B[0])
B1 = set(B[1])

mask1 = np.isin(A,list(B0)).any(axis=1)
mask2 = np.isin(A,list(B1)).any(axis=1)

combined_mask = np.logical_and(mask1,mask2)

print("Selected Rows Of A:", A[combined_mask])


Original Array A: [[0 0 7]
 [5 3 8]
 [5 6 2]
 [2 0 2]
 [5 6 4]
 [6 8 0]
 [1 8 5]
 [9 7 8]]
Original Array B: [[5 9]
 [1 4]]
Selected Rows Of A: [[5 6 4]
 [1 8 5]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

**5.** Given a 10x3 matrix, find the rows consisting of non-equal values (e.g., row [2,2,3] remains, row [3,3,3] is removed)

In [39]:

A = np.random.randint(0, 2, size=(10, 3))
print("Original Array:", A)

first_column = A[:, 0:1]
is_equal_to_first = (A == first_column)
all_same = is_equal_to_first.all(axis=1)

mask = ~all_same
result = A[mask]
print("Result:",result)

Original Array: [[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 1 1]
 [1 0 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [1 0 0]
 [0 1 1]]
Result: [[0 0 1]
 [1 1 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 1 0]
 [1 0 0]
 [0 1 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

**6.** Given a two-dimensional array. Remove rows that are duplicates.

In [43]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3], # Duplicate of row 0
    [7, 8, 9],
    [4, 5, 6]  # Duplicate of row 1
])
print("Original Array:", arr)

unique_arr = np.unique(arr,axis=0)
print("Modified Array:", unique_arr)

Original Array: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]
Modified Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
# your code

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
# your code

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
# your code

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
# your code

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
# your code

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
# your code

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
# your code

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
# your code

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
# your code

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
# your code

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
# your code

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
# your code